name: 'Chromatic'

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: srv/frontend
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: srv/frontend
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
